#!/bin/bash
#
# NAME
#         build-watch - build a project when the source files are updated
#
# SYNOPSYS
#         ./build-watch COMMAND

STATE=`mktemp -d`
touch $STATE/src
touch $STATE/build

function set-state {
	find . -type f -not -path '*/\.*' -printf "%T+\t%p\n" | md5sum > $STATE/$1
}

function diff-state {
	diff $STATE/$1 $STATE/$2 || return 0
	return 1
}

function print-success {
	echo -e "build-watch: \e[32mBuild passed.\e[39m";
}

function print-error {
	echo -e "build-watch: \e[31mBuild failed !\e[39m";
}

while true
do 
	set-state src

	if diff-state src build; then
		echo "$@"
		set-state build && $@ && print-success || print-error
	fi

	sleep 1
done
