#!/bin/bash
#
# NAME
#         build-watch - build and run a project when the source files are updated
#
# SYNOPSYS
#         ./build-watch BUILD-COMMAND RUN-COMMAND

STATE=`mktemp -d`
touch $STATE/src
touch $STATE/build
touch $STATE/executable
touch $STATE/run

function set-state {
	find . -type -f -not -path '*/\.*' -printf "%T+\t%p\n" | md5sum > $STATE/$1
}

function diff-state {
	diff $STATE/$1 $STATE/$2 || return 0
	return 1
}

while true
do 
	set-state src

	if diff-state src build; then
		echo "$1"
		set-state build && $1 && set-state executable
	elif diff-state executable run; then
		echo "$2"
		set-state run   && $2
	fi

	sleep 2
done
